apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: "system:default/alice"
  type:  "service"
  lifecycle: "experimental"
  owner: "group:default/digitalservices"
metadata:
  name: "gfg"
  annotations:
    github.com/project-slug: katakam/testaf
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: gfg-dev
    backstage.io/kubernetes-id: "gfg"
    sonarqube.org/project-key: "gfg"
    grafana/tag-selector: "Kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="gfg"}
    prometheus.io/alert: all
  tags:
    - golang
    # - system:default/alice
    - "service"
    - "experimental"
  links:
    - url: https://gfg.
      title: Website
      icon: Website
    - url: https://grafana.test.com/
      title: Dashboard
      icon: dashboard
    - url: https://alerts.test.com/
      title: Alerts
      icon: alert
    - url: https://argocd.test.com/applications/gfg-dev?resource=
      title: ArgoCD
      icon: cloud
    - url: https://grafana.test.com/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=Prometheus&var-namespace=gfg&var-resolution=30s
      title: Logs
      icon: cloud
    - url: https://kiali.test.com/kiali/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=versionedApp&namespaces=gfg&duration=120&refresh=60000&idleNodes=true&layout=kiali-breadthfirst&namespaceLayout=kiali-dagre
      title: Kiali
      icon: cloud
