name: Rollback 🔙

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Set Docker Image Tag to RollBack"
        required: true

jobs:
  env:
    uses: katakam/.github/.github/workflows/env.yaml@main

  rollback:
    uses: katakam/.github/.github/workflows/rollback.yaml@main
    secrets: inherit
    with:
      tag: 
      repository: 
    needs:
      - env

  notify:
    uses: katakam/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - rollback
